version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 20
    commands:
      - echo "Installing source NPM dependencies..."
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo "Build Started.."
      - ng build --configuration=production
      # - cp -r dist/assets .  # Copy the assets folder to the root directory
      # - cp dist/* .     
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths:  yes